/* tslint:disable */
/* eslint-disable */
/**
 * Learning Management System API
 * Learning Management System APIs for managing students, staff, courses, enrollments, authentication, attendance, assessments, and academic operations with secure JWT-based authorization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

